### ISSUE TITLE
windows consol has two cursors after restarting

### ISSUE THREAD

**Issue by LeeLux** [Jon-Kle/DB-Manager#20]
when I open the projekt in windows consol and use the restart command you now have the normal "cursor" after ---(DB-Manager)> |
but also next line open in the middle but in the position where my parh from the Projekt would end. 
![image](https://user-images.githubusercontent.com/104869480/186139010-45aab226-894f-45cf-80b9-1cdba3f9a979.png)

So boath are aktiv at the same time. Idk
When I try to tab complete it show the DB-manager command!
Pritty much its messed up. If you ctro+c you can get this error message:
```Traceback (most recent call last):
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 1139, in <module>
    cli.cmdloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\cmd.py", line 126, in cmdloop
    line = input(self.prompt)
KeyboardInterrupt```

**Comment by Jon-Kle** [comment]
The debug messages at restart are removed now, so maybe try it again with the new changes.
The ctrl+c error message is completely normal by the way
