### ISSUE TITLE
requests.exceptions.JSONDecodeError in every branch

### ISSUE THREAD

**Issue by LeeLux** [Jon-Kle/DB-Manager#44]
I just wanted to check the concept of my code but I got the following error message. I switched branches because my branch was really up to date but I got this error on every branch I checked. I looked it up but I didn't want to try everything because @Jon-Kle wrote this and it works for him and he is more knowledge than I am.

```PS C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src> python3 main.py
    -- DB-Manager --
Traceback (most recent call last):
es\Python310\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 1408, in <module>
    cli.cmdloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\cmd.py", line 105, in cmdloop
    self.preloop()
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 853, in preloop
    raise e
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 833, in preloop
    api1.check()
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 371, in check
    self.get_values()
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 416, in get_values
    data = self.request()
  File "C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src\main.py", line 399, in request
    return r.json()  # parses dict of json response
  File "C:\Users\Leander\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by Jon-Kle** [comment]
Can you insert this above `return r.json()` and send me the string he prints please?
```
print(r.text)
```

**Comment by LeeLux** [comment]
So the problem was what the secret wasn't revealed so to data for the request was empty, so wrong.

So maybe we add a check if all data in the config is not empty or so.
